import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#161616] text-[#D4D4D4]">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
